### ISSUE TITLE
Exploratory Data Analysis (EDA) on a Dataset

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Data-Science-Projects#1]
Choose a dataset of interest (e.g., a CSV file containing information about a topic you're curious about) and perform EDA. Explore the data, visualize key trends, and gain insights using libraries like Pandas, Matplotlib, and Seaborn.

**Comment by laibashakil** [comment]
Hi, I can do this. Kindly assign me this issue. Thanks

**Comment by Abhayg444** [comment]
Adding my EDA on the Global Temperature Analysis.
